"use client";

import { Cover } from "@/components/Images/Cover";
import Toolbar from "@/components/Toolbars/Toolbar";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { useMutation, useQuery } from "convex/react";
import dynamic from "next/dynamic";
import React, { useMemo } from "react";

// Params types are async in Next.js 15; keep a permissive `any` here for the
// client page so the component can continue to read params synchronously.
/**
 * Route parameters provided by Next.js for the document page.
 */
type DocumentPageProps = {
  params: any;
};

/**
 * Editor page for a single document, including cover, toolbar, and rich text editor.
 * Reads the document via Convex queries and persists updates as the user types.
 *
 * @param param0 Route parameters containing the document id.
 * @param param0.params Route params destructured for readability.
 * @returns Document editor experience or null when the document is missing.
 * @see https://docs.convex.dev/database/queries
 */
const DocumentPage: React.FC<DocumentPageProps> = ({ params }) => {
  /**
   * Dynamically import the editor component to prevent it from being bundled.
   * The editor cannot be rendered by the server.
   */
  const Editor = useMemo(
    () => dynamic(() => import("@/components/Editors/Editor"), { ssr: false }),
    []
  );

  /**
   * Fetch the document by its ID.
   * The document to be fetched is the currently opened one.
   * The ID of the currently opened document is read from the URL params.
   */
  const document = useQuery(api.documents.getById, {
    documentId: params.documentId,
  });

  /**
   * Update the document by its ID.
   * The document to be updated is the currently opened one.
   * The ID of the currently opened document is read from the URL params.
   */
  const update = useMutation(api.documents.update);

  /**
   * Persists editor changes by storing the serialized BlockNote document in Convex.
   *
   * @param content Serialized BlockNote document string generated by the editor.
   */
  const onChange = (content: string) => {
    update({
      id: params.documentId,
      content,
    });
  };

  // while the document is being fetched display a skeleton loading animation
  if (document === undefined) {
    return (
      <div>
        <Cover.Skeleton />
        <div className="md:max-w-3xl lg:max-w-4xl mx-auto mt-10">
          <div className="space-y-4 pl-8 pt-4">
            <Skeleton className="h-14 w-[50%]" />
            <Skeleton className="h-4 w-[80%]" />
            <Skeleton className="h-4 w-[40%]" />
            <Skeleton className="h-4 w-[60%]" />
          </div>
        </div>
      </div>
    );
  }

  // if the document does not exist display a message
  if (document === null) {
    return <div>Not found</div>;
  }

  return (
    <div className="pb-40">
      <Cover url={document.coverImage} />
      <div className="md:max-w-3xl lg:max-w-4xl mx-auto">
        <Toolbar initialData={document} />
        <Editor onChange={onChange} initialContent={document.content} />
      </div>
    </div>
  );
};

export default DocumentPage;
