"use client";

import { useMutation, useQuery } from "convex/react";
import dynamic from "next/dynamic";
import { notFound } from "next/navigation";
import type React from "react";
import { use, useMemo } from "react";
import { Cover } from "@/components/image/cover";
import Toolbar from "@/components/toolbar/toolbar";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";

/**
 * Route params provided to the preview page.
 * In Next.js 16, params is a Promise that must be awaited.
 */
type PreviewDocumentIdPageProps = {
  params: Promise<{ documentId: Id<"documents"> }>;
};

/**
 * Public document preview page that renders read-only content for shared notes.
 * Shares much of the same layout as the private editor but locks editing interactions.
 *
 * @param param0 Route parameters describing the document to preview.
 * @param param0.params Route params destructured for clarity.
 * @returns Read-only preview of the published document or null if absent.
 * @see https://docs.convex.dev/database/queries
 */
const PreviewDocumentPage: React.FC<PreviewDocumentIdPageProps> = (props) => {
  const params = use(props.params);
  /**
   * Dynamically import the editor component to prevent it from being bundled.
   * The editor cannot be rendered by the server.
   */
  const Editor = useMemo(
    () => dynamic(() => import("@/components/editor/editor"), { ssr: false }),
    [],
  );

  /**
   * Fetch the document by its ID.
   * The document to be fetched is the currently opened one.
   * The ID of the currently opened document is read from the URL params.
   */
  const document = useQuery(api.documents.getById, {
    documentId: params.documentId,
  });

  /**
   * Update the document by its ID.
   * The `update` function is from the Convex API.
   */
  const update = useMutation(api.documents.update);

  /**
   * Persists changes to keep content in sync when the owner updates previews.
   *
   * @param content Serialized BlockNote document string generated by the editor.
   */
  const onChange = (content: string) => {
    update({
      id: params.documentId, // same ID
      content, // updated content
    });
  };

  // while the document is being fetched display a skeleton loading animation
  if (document === undefined) {
    return (
      <div>
        <Cover.Skeleton />
        <div className="mx-auto mt-10 md:max-w-3xl lg:max-w-4xl">
          <div className="space-y-4 pt-4 pl-8">
            <Skeleton className="h-14 w-[50%]" />
            <Skeleton className="h-4 w-[80%]" />
            <Skeleton className="h-4 w-[40%]" />
            <Skeleton className="h-4 w-[60%]" />
          </div>
        </div>
      </div>
    );
  }

  // if the document is not found trigger not-found UI
  if (document === null) {
    return notFound();
  }

  return (
    <div className="pb-40">
      {/* Cover Image */}
      <Cover preview url={document.coverImage} />
      <div className="mx-auto md:max-w-3xl lg:max-w-4xl">
        <Toolbar preview initialData={document} />
        <Editor
          editable={false}
          onChange={onChange}
          initialContent={document.content}
        />
      </div>
    </div>
  );
};

export default PreviewDocumentPage;
